// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvxhufovszecptybzuiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2eGh1Zm92c3plY3B0eWJ6dWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MzAxMzEsImV4cCI6MjA2ODEwNjEzMX0.47yyx16MO7H3pxA-pIFoRNvUF9wQyBN4o1Bm6ONVobw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});